import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Password_generator from "../components/password_components/Password_generator";
import Hero_section from "../components/password_components/Hero_section";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Lazar Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>
      <Header />
      <Hero_section />
    </div>
  );
};

export default Home;
